// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as embed$0 from "../../embed/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../github.com/wailsapp/wails/v3/pkg/application/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function HideTipsWindow(): $CancellablePromise<void> {
    return $Call.ByID(3042050268);
}

export function OpenSecondWindow(): $CancellablePromise<void> {
    return $Call.ByID(2561160154);
}

export function OpenTipsWindow(): $CancellablePromise<void> {
    return $Call.ByID(70083156);
}

export function SetApp(app: application$0.App | null, i18nFS: embed$0.FS, repo: $models.SuiStore | null): $CancellablePromise<void> {
    return $Call.ByID(3023151489, app, i18nFS, repo);
}

/**
 * 设置语言并更新菜单显示
 */
export function SetLanguage(lang: string): $CancellablePromise<void> {
    return $Call.ByID(1152097840, lang);
}
