// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class Hotkey {
    /**
     * 热键ID
     */
    "id": number;

    /**
     * 键码
     */
    "keycode": number;

    /**
     * 修饰键
     */
    "modifiers": number;

    /** Creates a new Hotkey instance. */
    constructor($$source: Partial<Hotkey> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("keycode" in $$source)) {
            this["keycode"] = 0;
        }
        if (!("modifiers" in $$source)) {
            this["modifiers"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Hotkey instance from a string or object.
     */
    static createFrom($$source: any = {}): Hotkey {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Hotkey($$parsedSource as Partial<Hotkey>);
    }
}

export class TipInfo {
    "id": number;
    "type": string;
    "category": string;
    "title": string;
    "desc": string;
    "createdAt": number;
    "expireat": number;
    "state": number;
    "pinned": number;
    "pinnedat": number | null;
    "snoozeat": number | null;
    "snoozecount": number;

    /** Creates a new TipInfo instance. */
    constructor($$source: Partial<TipInfo> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("type" in $$source)) {
            this["type"] = "";
        }
        if (!("category" in $$source)) {
            this["category"] = "";
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("desc" in $$source)) {
            this["desc"] = "";
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = 0;
        }
        if (!("expireat" in $$source)) {
            this["expireat"] = 0;
        }
        if (!("state" in $$source)) {
            this["state"] = 0;
        }
        if (!("pinned" in $$source)) {
            this["pinned"] = 0;
        }
        if (!("pinnedat" in $$source)) {
            this["pinnedat"] = null;
        }
        if (!("snoozeat" in $$source)) {
            this["snoozeat"] = null;
        }
        if (!("snoozecount" in $$source)) {
            this["snoozecount"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TipInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): TipInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TipInfo($$parsedSource as Partial<TipInfo>);
    }
}
