// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function Close(): $CancellablePromise<void> {
    return $Call.ByID(1355592200);
}

export function FindNextScheduled(now: number): $CancellablePromise<$models.TipInfo | null> {
    return $Call.ByID(951729845, now).then(($result: any) => {
        return $$createType1($result);
    });
}

export function GetHotkeys(): $CancellablePromise<$models.Hotkey[]> {
    return $Call.ByID(23462219).then(($result: any) => {
        return $$createType3($result);
    });
}

export function GetLatestTip(): $CancellablePromise<$models.TipInfo | null> {
    return $Call.ByID(1530230084).then(($result: any) => {
        return $$createType1($result);
    });
}

export function GetTips(): $CancellablePromise<$models.TipInfo[]> {
    return $Call.ByID(1462738058).then(($result: any) => {
        return $$createType4($result);
    });
}

export function InsTips(contentType: string, category: string, content: string, expireAt: number, snoozeAt: number): $CancellablePromise<void> {
    return $Call.ByID(1660750994, contentType, category, content, expireAt, snoozeAt);
}

export function Start(): $CancellablePromise<void> {
    return $Call.ByID(835708248);
}

export function Stop(): $CancellablePromise<void> {
    return $Call.ByID(1501773308);
}

/**
 * 同步过期的提示
 */
export function SyncExpiredTips(): $CancellablePromise<void> {
    return $Call.ByID(469752206);
}

/**
 * 快捷键修改
 */
export function UpHotkey(id: number, key: number, modifier: number): $CancellablePromise<void> {
    return $Call.ByID(3795952175, id, key, modifier);
}

/**
 * 延迟提示
 */
export function UpTipsDelayed(id: number, expireAt: number): $CancellablePromise<void> {
    return $Call.ByID(1189476615, id, expireAt);
}

export function UpTipsPinned(id: number, pinned: number): $CancellablePromise<void> {
    return $Call.ByID(523553905, id, pinned);
}

/**
 * 更新提示状态
 */
export function UpTipsState(id: number, state: number): $CancellablePromise<void> {
    return $Call.ByID(2892239320, id, state);
}

// Private type creation functions
const $$createType0 = $models.TipInfo.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $models.Hotkey.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = $Create.Array($$createType0);
